Jam/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
#     password_reset_complete, PasswordResetView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from dbbackup_ui.views import BackupView

urlpatterns = [
    path('admin_panel/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('register.urls')),
    path('', include('SPC_main.urls')),
    path('', include('setting.urls')),
    path('', include('online_match.urls')),
    path('', include('IAC_cup.urls')),
    path('password_reset', PasswordResetView.as_view(), name='reset_password'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('password_reset', password_reset, name='reset_password'),
    # path('password_reset/done', password_reset_done, name='password_reset_done'),
    # url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     password_reset_confirm, name='password_reset_confirm'),
    # path('password_reset/complete',password_reset_complete, name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[1])
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SPC_main/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView
from .views import *

app_name = 'SPC_main'
urlpatterns = [
    path('old_jaam/', old_SPC_main_page, name='old_SPC_main_page'),
    path('index/', SPC_main_page, name='SPC_main_page'),
    path('logout/', team_logout, name='logout'),
    path('old_table/', old_table_view, name='old-table-spc'),
    path('table/', table_view, name='table-spc'),
    path('cup/', cup_view, name='cup-view'),
    path('cup-tables/', jaam_table_view, name='jaam-tables-view'),
    url(r'^add_team_ajax/$', add_team_to_cup, name='file_upload_ajax'),
]

online_match/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import RedirectView

from .views import *

urlpatterns = [
    path('old_play/', online_match, name='old_online_match'),
    path('play/', online_match, name='online_match'),
    path('old_log/', log_view, name='old_log'),
    path('log/', log_view, name='log'),
    url(r'^play_online_ajax/$', play_online_ajax, name='play_online_ajax'),
    url(r'^file_upload_ajax/$', upload_view, name='file_upload_ajax'),
]
app_name = 'online_match'

templates/base2_0/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    {% load staticfiles %}
    {% load widget_tweaks %}
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-global.css' %}">

    {#    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no"/>#}
    <meta name="viewport"
          content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no"/>
    <meta charset="utf-8">
    {% block head %}
    {% endblock %}


</head>
<body>
<div class="row cnt" style="direction: rtl">
    {% include 'base2_0/menu_item.html' %}
    {% include 'base2_0/menu_team_discription.html' %}
    <div class="col s12 m12 l8 xl8  pull-l4 pull-xl4 content" id="container">
        {% include 'base2_0/navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>

</div>

{% block scripts %}{% endblock %}
<script src='{% static "New_UI_V2/js/materialize.js" %}'></script>
<script>
    M.AutoInit();

</script>

</body>
</html>

templates/base2_0/menu_item.html
{% load static %}
<div class="hide-on-med-and-down col s12 m12 l1 xl1  push-l11 push-xl11 content">

    <div class="menu-items hide-on-med-and-down">
        <img src="{% static 'img/jaam.png' %}"
             style="width: 70%; margin-right: 15%;"
             class="hide-on-med-and-down">
        <a href="{% url 'SPC_main:SPC_main_page' %}">
                <span class="menu-icon icon-info tooltipped" data-position="left"
                      data-tooltip="اطلاعات تیم" id="team_detail_item"></span>
        </a>
        <a href="{% url 'online_match:online_match' %}">
                <span class="menu-icon icon-friendly tooltipped" data-position="left"
                      data-tooltip="بازی دوستانه" id="friendly_item"></span>
        </a>
        <a href="{% url 'SPC_main:table-spc' %}">
            <span class="menu-icon icon-cup tooltipped" data-position="left" data-tooltip="جدول جام"
                  id="cup_item"></span>
        </a>
        <a href="{% url 'SPC_main:jaam-tables-view' %}">
                <span class="menu-icon icon-competition tooltipped" data-position="left"
                      data-tooltip="جدول رقابت‌ها" id="table_jaam_item"></span>
        </a>
        <a href="{% url 'online_match:log' %}">
            <span class="menu-icon icon-result tooltipped" data-position="left"
                  data-tooltip="نتایج" id="log_item"></span>
        </a>

    </div>
</div>
<div class="show-on-medium-and-down hide-on-large-only hide-on-extra-large-only col s12 m12 l1 xl1  push-l11 push-xl11 side ">
    <img src='{% static "img/jaam.png" %}' style="height: 70%; margin-right: 20px; margin-top: 10px ;"
         class="show-on-medium-and-down hide-on-large-only hide-on-extra-large-only ">
    <div class="menu-items-mob hide-on-med-and-up show-on-medium">
        <a href="{% url 'online_match:log' %}" class="inline">
            <span class="menu-icon-mob icon-result tooltipped" data-position="bottom"
                  data-tooltip="نتایج" id="log_mobile_item"></span>
        </a>
        <a href="{% url 'SPC_main:jaam-tables-view' %}" class="inline">
                <span class="menu-icon-mob icon-competition tooltipped" data-position="bottom"
                      data-tooltip="جدول رقابت ها" id="table_jaam_mobile_item"></span>
        </a>
        <a href="{% url 'SPC_main:table-spc' %}" class="inline">
            <span class="menu-icon-mob icon-cup tooltipped" data-position="bottom"
                  data-tooltip="جدول جام" id="cup_mobile_item"></span>
        </a>
        <a href="{% url 'online_match:online_match' %}" class="inline">
                <span class="menu-icon-mob icon-friendly tooltipped" data-position="bottom"
                      data-tooltip="بازی دوستانه" id="friendly_mobile_item"></span>
        </a>

        <a href="{% url 'SPC_main:SPC_main_page' %}" class="inline">
                <span class="menu-icon-mob icon-info tooltipped" data-position="bottom"
                      data-tooltip="اطلاعات تیم" id="team_detail_mobile_item"></span>
        </a>
    </div>
</div>

templates/base2_0/menu_item_IAC.html
{% load static %}
<div class="hide-on-med-and-down col s12 m12 l1 xl1  push-l11 push-xl11 content">

    <div class="menu-items hide-on-med-and-down">
        <img src="{% static 'img/jaam.png' %}"
             style="width: 70%; margin-right: 15%;"
             class="hide-on-med-and-down">
        <a href="{% url 'SPC_main:SPC_main_page' %}">
                <span class="menu-icon icon-info tooltipped" data-position="left"
                      data-tooltip="اطلاعات تیم" id="team_detail_item"></span>
        </a>
        <a href="{% url 'online_match:online_match' %}">
            <span class="menu-icon icon-result tooltipped" data-position="left"
                  data-tooltip="مجموعه دادگان" id="friendly_item"></span>
        </a>
        <a href="{% url 'SPC_main:jaam-tables-view' %}">
                <span class="menu-icon icon-competition tooltipped" data-position="left"
                      data-tooltip="جدول رقابت‌ها" id="table_jaam_item"></span>
        </a>

    </div>
</div>
<div class="show-on-medium-and-down hide-on-large-only hide-on-extra-large-only col s12 m12 l1 xl1  push-l11 push-xl11 side ">
    <img src='{% static "img/jaam.png" %}' style="height: 70%; margin-right: 20px; margin-top: 10px ;"
         class="show-on-medium-and-down hide-on-large-only hide-on-extra-large-only ">
    <div class="menu-items-mob hide-on-med-and-up show-on-medium">
        <a href="{% url 'SPC_main:jaam-tables-view' %}" class="inline">
                <span class="menu-icon-mob icon-competition tooltipped" data-position="bottom"
                      data-tooltip="جدول رقابت ها" id="table_jaam_mobile_item"></span>
        </a>
        <a href="{% url 'online_match:online_match' %}" class="inline">
            <span class="menu-icon-mob icon-result tooltipped" data-position="bottom"
                  data-tooltip="مجموعه دادگان" id="friendly_mobile_item"></span>
        </a>

        <a href="{% url 'SPC_main:SPC_main_page' %}" class="inline">
                <span class="menu-icon-mob icon-info tooltipped" data-position="bottom"
                      data-tooltip="اطلاعات تیم" id="team_detail_mobile_item"></span>
        </a>


    </div>
</div>

templates/base2_0/menu_team_discription.html
{% load static %}
<div class="col s12 m12 l3 xl3  push-l7 push-xl7 info">
    <div class="hide-on-med-and-down">
        <div class="row" style="height: 100%;">
            <div>
                <img src="{{ login_team.logo_image.url }}" class="team-avatar">

            </div>
            <div class="team-info">
                <h3 style="direction: ltr" id="username">
                    {{ user.username }}
                </h3>
                <h6 id="email">
                    {{ user.email|truncatechars:25 }}
                </h6>
            </div>
            <span>
            <div class="team-quote">
                <h6>
                    {{ login_team.team_bio|truncatewords:30 }}
                </h6>
            </div>
            </span>

        </div>
    </div>

    <div class="hide-on-med-and-up show-on-medium">
        <div class="row" style="height: 100%;">
            <div>
                <img src="{{ login_team.logo_image.url }}" class="team-avatar">

            </div>
            <div class="team-info" style="margin-right: 5px">
                <h4 style="direction: ltr" id="username-mobile">
                    {{ user.username|truncatechars:10 }}
                </h4>
                <h6 id="email-mobile">
                    {{ user.email|truncatechars:25 }}
                </h6>
            </div>
        </div>
    </div>
    <script src='{% static "js/jquery-3.1.1.min.js" %}'></script>
    <script src="{% static 'js/jaam/dynamic_font.js' %}"></script>

</div>

templates/base2_0/navbar.html
<!DOCTYPE html>
<div class="nav-menu" style="z-index: 2000;">
    <div class="logout">
        <span class="icon-logout" onclick="location.href='/logout/'" id="logout-icon" name="logout-icon"></span>
        <label for="logout-icon" onclick="location.href='/logout/'">خروج</label>
    </div>
    <div class="edit-info">
        <label onclick="location.href= '/setting/'" id="setting_item">ویرایش اطلاعات</label>
    </div>
</div>