Jam/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
#     password_reset_complete, PasswordResetView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from dbbackup_ui.views import BackupView

urlpatterns = [
    path('admin_panel/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('register.urls')),
    path('', include('SPC_main.urls')),
    path('', include('setting.urls')),
    path('', include('online_match.urls')),
    path('', include('IAC_cup.urls')),
    path('password_reset', PasswordResetView.as_view(), name='reset_password'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('password_reset', password_reset, name='reset_password'),
    # path('password_reset/done', password_reset_done, name='password_reset_done'),
    # url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     password_reset_confirm, name='password_reset_confirm'),
    # path('password_reset/complete',password_reset_complete, name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[1])
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SPC_main/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView
from .views import *

app_name = 'SPC_main'
urlpatterns = [
    path('old_jaam/', old_SPC_main_page, name='old_SPC_main_page'),
    path('index/', SPC_main_page, name='SPC_main_page'),
    path('logout/', team_logout, name='logout'),
    path('old_table/', old_table_view, name='old-table-spc'),
    path('table/', table_view, name='table-spc'),
    path('cup/', cup_view, name='cup-view'),
    path('cup-tables/', jaam_table_view, name='jaam-tables-view'),
    url(r'^add_team_ajax/$', add_team_to_cup, name='file_upload_ajax'),
]

online_match/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import RedirectView

from .views import *

urlpatterns = [
    path('old_play/', online_match, name='old_online_match'),
    path('play/', online_match, name='online_match'),
    path('old_log/', log_view, name='old_log'),
    path('log/', log_view, name='log'),
    url(r'^play_online_ajax/$', play_online_ajax, name='play_online_ajax'),
    url(r'^file_upload_ajax/$', upload_view, name='file_upload_ajax'),
]
app_name = 'online_match'

setting/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from .views import *

app_name = 'setting'
urlpatterns = [
    # path('setting/', setting_page, name='setting'),
    re_path(r'setting(?P<active_member>\d*)/', setting_page, name='setting'),
    path('old_setting/', setting_page, name='old_setting'),
    url(r'^mentor_ajax/$', mentor_ajax, name='mentor_ajax'),

    # path('test_ajax',test_ajax,name='test_ajax'),s
]

templates/base_2_1/base.html
<!DOCTYPE html>
<html lang="en" style="overflow-y: hidden">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}    {% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href='{% static "New_UI_V2/css/materialize.css" %}'
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href='{% static "New_UI_V2/css/global_css.css" %}'>
    <link type="text/css" rel="stylesheet" href='{% static "New_UI_V2/css/base.css" %}' media="screen,projection"/>

    <link type="image/png" rel="icon" href="{% static 'img/jaam.png' %}">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    {% block head %}
    {% endblock %}

    <!--Let browser know website is optimized for mobile-->

</head>
<body>
<div class="row  cnt  top-margin-main  " style="direction: rtl;height: 98%">
    <!-- right menu-->
    {% include 'base_2_1/icon_menu.html' %}
    <!-- -->

    <!-- info menu -->
    {% include 'base_2_1/info_menu.html' %}
    <!-- -->


    <!-- content-->
    {% block content %}
    {% endblock %}
    <!-- -->

</div>
<!--JavaScript at end of body for optimized loading-->
<script type="text/javascript" src='{% static "New_UI_V2/js/materialize.js" %}'></script>
<script src='{% static "js/jquery-3.1.1.min.js" %}'></script>
<script src="{% static 'js/jaam/item_active.js' %}"></script>
<script src="{% static 'js/jaam/dynamic_font.js' %}"></script>
<script>
    M.AutoInit();
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.sidenav');
        let options = {
            edge: "right",
            draggable: true
        };
        var instances = M.Sidenav.init(elems, options);
    });
</script>
{% block script %}
{% endblock %}
</body>
</html>

templates/base_2_1/icon_menu.html
<!DOCTYPE html>
{% if login_team.competition.competition_level < 3 %}
    <div class="hide-on-med-and-down col l1 xl1  push-l11 push-xl11 content  center-align full-height">
        <div class="menu-items hide-on-med-and-down">
            <!--  <br style="font-size: 1vw"> -->
            <br>
            {% load static %}
            <img src="{% static 'img/jaam.png' %}"
                 class=" hide-on-med-and-down responsive-img">
            <a class="row center-block no-margins" href="{% url 'SPC_main:SPC_main_page' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="اطلاعات تیم" id="team_detail_item">info_outline</i>
            </a>
            <a class="row center-block no-margins" href="{% url 'setting:setting' 0 %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="ویرایش اطلاعات" id="team_setting_item">settings</i>
            </a>
            <a class="row center-block no-margins" href="{% url 'online_match:online_match' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="بازی دوستانه" id="friendly_item">videogame_asset</i>
            </a>
            <a class="row center-block no-margins" href="{% url 'SPC_main:jaam-tables-view' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="جدول رقابت‌ها" id="table_jaam_item">show_chart</i>
            </a>
            <a class="row center-block no-margins" href="{% url 'online_match:log' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="نتایج" id="log_item">assignment</i>
            </a>

            <a class="row center-block no-margins" href="{% url 'SPC_main:logout' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="خروج" id="logout_item">exit_to_app</i>
            </a>

        </div>
    </div>
    <div class="show-on-medium-and-down hide-on-large-only hide-on-extra-large-only " style="height: 5%">
        <nav class="" role="navigation"
             style=" background-color: rgb(214, 209, 219) ;color: black; font-size:20px;height: 100%">
            <a href="#" data-target="slide-out" class="sidenav-trigger right" style="height: 100%">
                <i class="material-icons" style="line-height: 100%">menu</i>
            </a>
            <ul id="slide-out" class="sidenav right-align " style="padding: unset">
                <img src="{{ login_team.logo_image.url }}"
                     class="team-avatar responsive-img  top-margin-main center-block"
                     style="width: 50%">
                <a class="row " href="{% url 'SPC_main:SPC_main_page' %}">
                    <i class="material-icons menu-icon-materialize" id="team_detail_mobile_item">
                        <span class="menu-icon-mob-size">
                            اطلاعات تیم
                        </span>
                        info_outline
                    </i>
                </a>
                <a class="row " href="{% url 'setting:setting' 0 %}">
                    <i class="material-icons menu-icon-materialize" id="team_setting_mobile_item">
                        <span class="menu-icon-mob-size">
                            ویرایش
                        </span>
                        settings
                    </i>
                </a>
                <a class="row " href="{% url 'online_match:online_match' %}">
                    <i class="material-icons menu-icon-materialize" id="friendly_mobile_item">
                        <span class="menu-icon-mob-size">
                            بازی دوستانه
                        </span>
                        videogame_asset </i>
                </a>
                <a class="row " href="{% url 'SPC_main:jaam-tables-view' %}">
                    <i class="material-icons menu-icon-materialize" id="table_jaam_mobile_item">
                        <span class="menu-icon-mob-size">
                            جدول رقابت
                        </span>
                        show_chart </i>
                </a>
                <a class="row " href="{% url 'online_match:log' %}">
                    <i class="material-icons menu-icon-materialize" id="log_mobile_item">
                        <span class="menu-icon-mob-size">
                            نتایج
                        </span>
                        assignment
                    </i>
                </a>
                <a class="row " href="{% url 'SPC_main:logout' %}">
                    <i class=" material-icons menu-icon-materialize">
                    <span class="menu-icon-mob-size">
                                    خروج
                    </span>
                        exit_to_app
                    </i>
                </a>
            </ul>
        </nav>
    </div>
{% else %}

    <div class="hide-on-med-and-down col l1 xl1  push-l11 push-xl11 content  center-align full-height">
        <div class="menu-items hide-on-med-and-down">
            <!--  <br style="font-size: 1vw"> -->
            <br>
            {% load static %}
            <img src="{% static 'img/jaam.png' %}" class=" hide-on-med-and-down responsive-img">
            <a class="row center-block no-margins" href="{% url 'SPC_main:SPC_main_page' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="اطلاعات تیم" id="team_detail_item">info_outline</i>
            </a>
            <a class="row center-block no-margins" href="{% url 'setting:setting' 0 %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="ویرایش اطلاعات" id="team_setting_item">settings</i>
            </a>
            <a class="row center-block no-margins" href="{% url 'SPC_main:jaam-tables-view' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="جدول رقابت‌ها" id="table_jaam_item">show_chart</i>
            </a>
            <a class="row center-block no-margins" href="{% url 'SPC_main:logout' %}">
                <i class="material-icons menu-icon-materialize tooltipped" data-position="left"
                   data-tooltip="خروج" id="logout_item">exit_to_app</i>
            </a>

        </div>
    </div>
    <div class="show-on-medium-and-down hide-on-large-only hide-on-extra-large-only " style="height: 5% !important;">
        <nav class="" role="navigation"
             style=" background-color: rgb(214, 209, 219) ;color: black; font-size:20px;height: 100%">
            <a href="#" data-target="slide-out" class="sidenav-trigger right" style="height: 100%">
                <i class="material-icons" style="line-height: 100%">menu</i>
            </a>
            <ul id="slide-out" class="sidenav right-align " style="padding: unset">
                <img src="{{ login_team.logo_image.url }}"
                     class="team-avatar responsive-img  top-margin-main center-block"
                     style="width: 50%">
                <a href="{% url 'SPC_main:SPC_main_page' %}">
                    <i class="material-icons menu-icon-materialize" id="team_detail_mobile_item">
                        <span class="menu-icon-mob-size">
                            اطلاعات تیم
                        </span>
                        info_outline
                    </i>
                </a>
                <a href="{% url 'setting:setting' 0 %}">
                    <i class="material-icons menu-icon-materialize" id="team_setting_mobile_item">
                        <span class="menu-icon-mob-size">
                            ویرایش
                        </span>
                        settings
                    </i>
                </a>
                <a href="{% url 'SPC_main:jaam-tables-view' %}">
                    <i class="material-icons menu-icon-materialize" id="table_jaam_mobile_item">
                        <span class="menu-icon-mob-size">
                            جدول رقابت
                        </span>
                        show_chart </i>
                </a>
                <a href="{% url 'SPC_main:logout' %}">
                    <i class=" material-icons menu-icon-materialize">
                        <span class="menu-icon-mob-size">
                                خروج
                        </span>
                        exit_to_app
                    </i>
                </a>
            </ul>
        </nav>
    </div>
{% endif %}

templates/base_2_1/info_menu.html
<!DOCTYPE html>
<div class="hide-on-med-and-down col l3 xl3 content2 push-l7 push-xl7 info full-height">

    <div class="hide-on-med-and-down top-margin-main">

        <div class="row">
            <div>
                <img src="{{ login_team.logo_image.url }}" class="team-avatar responsive-img center-block"
                     style="width: 75%">
            </div>
            <div class="team-info center-align">
                <h3 style="direction: ltr; font-size: 3vw" id="username">
                    {{ user.username }}
                </h3>
            </div>

            <div class=" center-align">
                <h6>
                    {{ login_team.team_bio|truncatewords:30 }}
                </h6>
            </div>



        </div>
    </div>

    <div class="hide-on-med-and-up show-on-medium">
        <div class=" row col s5 m5">
            <img src="{{ login_team.logo_image.url }}" class="team-avatar responsive-img">
        </div>
        <div class="row col s7 m7 center-align">
            <div>
                <div class="team-info">
                    <h4 id="username-mobile">
                        {{ user.username }}
                    </h4>
                </div>
            </div>
        </div>

    </div>

</div>