Jam/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
#     password_reset_complete, PasswordResetView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from dbbackup_ui.views import BackupView

urlpatterns = [
    path('admin_panel/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('register.urls')),
    path('', include('SPC_main.urls')),
    path('', include('setting.urls')),
    path('', include('online_match.urls')),
    path('', include('IAC_cup.urls')),
    path('password_reset', PasswordResetView.as_view(), name='reset_password'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('password_reset', password_reset, name='reset_password'),
    # path('password_reset/done', password_reset_done, name='password_reset_done'),
    # url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     password_reset_confirm, name='password_reset_confirm'),
    # path('password_reset/complete',password_reset_complete, name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[1])
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SPC_main/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView
from .views import *

app_name = 'SPC_main'
urlpatterns = [
    path('old_jaam/', old_SPC_main_page, name='old_SPC_main_page'),
    path('index/', SPC_main_page, name='SPC_main_page'),
    path('logout/', team_logout, name='logout'),
    path('old_table/', old_table_view, name='old-table-spc'),
    path('table/', table_view, name='table-spc'),
    path('cup/', cup_view, name='cup-view'),
    path('cup-tables/', jaam_table_view, name='jaam-tables-view'),
    url(r'^add_team_ajax/$', add_team_to_cup, name='file_upload_ajax'),
]

online_match/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import RedirectView

from .views import *

urlpatterns = [
    path('old_play/', online_match, name='old_online_match'),
    path('play/', online_match, name='online_match'),
    path('old_log/', log_view, name='old_log'),
    path('log/', log_view, name='log'),
    url(r'^play_online_ajax/$', play_online_ajax, name='play_online_ajax'),
    url(r'^file_upload_ajax/$', upload_view, name='file_upload_ajax'),
]
app_name = 'online_match'

setting/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from .views import *

app_name = 'setting'
urlpatterns = [
    # path('setting/', setting_page, name='setting'),
    re_path(r'setting(?P<active_member>\d*)/', setting_page, name='setting'),
    path('old_setting/', setting_page, name='old_setting'),
    url(r'^mentor_ajax/$', mentor_ajax, name='mentor_ajax'),

    # path('test_ajax',test_ajax,name='test_ajax'),s
]

SPC_main/models.py
from django.db import models
from main.models import Competition
from register.models import Team
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Cup(models.Model):
    cup_number = models.IntegerField(verbose_name=_("Cup Number"))
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name=_("Competition"))
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name=_("Team"))

    def __str__(self):
        return self.team.user_team.username + str(self.cup_number)

    class Meta:
        verbose_name = _("SPC Cup")
        verbose_name_plural = _("SPC Cups")
        ordering = ['competition']


class Tournament(models.Model):
    date = models.DateTimeField()
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)

SPC_main/views.py
from django.http import JsonResponse
from django.shortcuts import HttpResponseRedirect, loader, HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from register.models import Team
from .models import Cup
from online_match.models import Dataset


@login_required(login_url='/login', redirect_field_name='')
def old_SPC_main_page(request):
    print(request.META.get("upload_code", 0))
    print(request.user)
    team = request.user.Teams.all()[0]
    team_member = team.Users.all()
    user_require = 2 if team.competition.competition_level < 3 else 1
    print(user_require, team.competition.competition_level)
    if len(team_member) < user_require:
        return redirect("setting:setting", None)
    for member in team_member:
        print(member.user_lname)
    context = {
        'login_team': team,
        'members': team_member
    }
    if team.competition.competition_level < 3:
        template = loader.get_template('Old/extend/jaam_spc.html')
    else:
        template = loader.get_template('Old/extend/jaam_iac.html')
    return HttpResponse(template.render(context, request))


@login_required(login_url="/login", redirect_field_name='')
def SPC_main_page(request):
    print(request.META.get("upload_code", 0))
    print(request.user)
    team = request.user.Teams.all()[0]
    team_member = team.Users.all().order_by("pk")
    user_require = 2 if team.competition.competition_level < 3 else 1
    print(user_require, team.competition.competition_level)
    if len(team_member) < user_require:
        return redirect("setting:setting", len(team_member) + 1)
    for member in team_member:
        print(member.user_lname)
    context = {
        'login_team': team,
        'members': team_member
    }
    if team.competition.competition_level < 3:
        print('jaam2')
        template = loader.get_template('2.1/index_spc.html')
    else:
        print('jaamiac')
        datasets = Dataset.objects.filter(competition=team.competition)
        context['datasets'] = datasets
        template = loader.get_template('2.1/index_IAC.html')
    return HttpResponse(template.render(context, request))


def team_logout(request):
    logout(request)
    return HttpResponseRedirect('/login')


@login_required(login_url='/login', redirect_field_name='')
def old_table_view(request):
    login_team = request.user.Teams.all()[0]
    if login_team.competition.competition_level < 3:
        print('jaam2')
        teams = Team.objects.filter(competition=login_team.competition.competition_level).all()
        teams = sorted(teams, key=lambda x: x.get_points(), reverse=True)
        template = loader.get_template('Old/extend/table_spc.html')
    else:
        print('jaamiac')
        template = loader.get_template('Old/extend/table_iac.html')
        teams = dict()
        teams['picture'] = Team.objects.filter(competition__competition_level=5).order_by('accuracy')
        teams['sound'] = Team.objects.filter(competition__competition_level=4).order_by('accuracy')
        teams['text'] = Team.objects.filter(competition__competition_level=3).order_by('accuracy')
    context = {
        'login_team': login_team,
        'teams': teams
    }
    return HttpResponse(template.render(context, request))


@login_required(login_url='/login', redirect_field_name='')
def table_view(request):
    login_team = request.user.Teams.all()[0]
    if login_team.competition.competition_level < 3:
        print('jaam2')
        teams = Team.objects.filter(competition=1).all()
        teams = sorted(teams, key=lambda x: x.get_points(), reverse=True)
        template = loader.get_template('cup_table.html')
    else:
        print('jaamiac')
        template = loader.get_template('Old/extend/table_iac.html')
        teams = dict()
        teams['picture'] = Team.objects.filter(competition__competition_level=5).order_by('accuracy')
        teams['sound'] = Team.objects.filter(competition__competition_level=4).order_by('accuracy')
        teams['text'] = Team.objects.filter(competition__competition_level=3).order_by('accuracy')
    context = {
        'login_team': login_team,
        'teams': teams
    }
    return HttpResponse(template.render(context, request))


@login_required(login_url='/login', redirect_field_name='')
def cup_view(request):
    if request.method == 'GET':
        print('GET')
        login_team = request.user.Teams.all()[0]
        teams = Cup.objects.filter(competition=login_team.competition)
        print(teams)
        is_play = len(Cup.objects.filter(team=login_team)) > 0
        context = {
            'login_team': login_team,
            'teams': teams,
            'is_play': is_play,
        }
        if login_team.competition.competition_level < 3:
            template = loader.get_template('SPC_main/templates/Old/extend/cup_spc.html')
        else:
            template = loader.get_template('SPC_main/templates/Old/extend/cup_iac.html')
        return HttpResponse(template.render(context, request))
    elif request.method == 'POST':
        print("POST", request.POST)


@login_required(login_url='/login', redirect_field_name='')
def jaam_table_view(request):
    login_team = request.user.Teams.all()[0]
    teams = dict()
    temp = Team.objects.filter(competition=1).all()
    teams['SPC'] = sorted(temp, key=lambda x: x.get_points(), reverse=True)
    teams['picture'] = Team.objects.filter(competition__competition_level=5).order_by('accuracy')
    teams['sound'] = Team.objects.filter(competition__competition_level=4).order_by('accuracy')
    teams['text'] = Team.objects.filter(competition__competition_level=3).order_by('accuracy')
    template = loader.get_template('2.1/jaam_tables.html')
    context = {
        'teams': teams,
        'login_team': login_team
    }
    return HttpResponse(template.render(context, request))


@csrf_exempt
def add_team_to_cup(request):
    login_team = request.user.Teams.all()[0]
    if len(Cup.objects.filter(team=login_team)) == 0:
        t = Cup(team=login_team, competition=login_team.competition, cup_number=1)
        t.save()
        return JsonResponse({
            'status': "Success"
        })
    return JsonResponse({
        'status': 'failed'
    })

SPC_main/templates/cup_table.html
<html>

<head>
    <title>
        {{ user.username }} |
    </title>
    {% load static %}
    <link rel="stylesheet" href='{% static "css/materialize.css" %}'>
    <link rel="stylesheet" href='{% static "css/style-global.css" %}'>
    <link rel="stylesheet" href='{% static "css/style-index.css" %}'>
    <link type="image/png" rel="icon" href="{% static 'img/jaam.png' %}">
    <meta name="viewport"
          content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no"/>
    <meta charset="utf-8">
</head>

<body>


<div class="row cnt" style="direction: rtl">
    {% include 'base2_0/menu_item.html' %}


    {% include 'base2_0/menu_team_discription.html' %}


    <div class="col s12 m12 l8 xl8  pull-l4 pull-xl4 content">
        {% include 'base2_0/navbar.html' %}

        <div class="section table-container">
            <h3 class="center">
                جدول لیگ اشاره گر مقدماتی
            </h3>
            <table class="highlight centered responsive-table">
                <thead>
                <tr>
                    <th>تیم</th>
                    <th>دانشگاه</th>
                    <th>بازی</th>
                    <th>امتیاز</th>
                    <th>کلاس</th>
                </tr>
                </thead>

                <tbody>
                {% for team in teams %}
                <tr>
                    <td>{{ team.user_team.username }}</td>
                    <td>{{ team.university.university_name }}</td>
                    <td>{{ team.total_games }}</td>
                    <td>{{ team.get_points }}</td>
                    <td>A</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


    </div>

</div>
<script src='{% static "js/jquery-3.1.1.min.js" %}'></script>
<script src="{% static 'js/jaam/item_active.js' %}"></script>
<script src='{% static "New_UI_V2/js/materialize.js" %}'></script>
<script>
    M.AutoInit();

</script>
</body>

</html>

SPC_main/templates/index_IAC.html
<html>

<head>
    <title>
        {{ user.username }} | پنل مدیریت تیم
    </title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href='{% static "css/materialize.css" %}'>
    <link rel="stylesheet" href='{% static "css/style-global.css" %}'>
    <link rel="stylesheet" href='{% static "css/style-index.css" %}'>
    <link type="image/png" rel="icon" href="{% static 'img/jaam.png' %}">

    <meta name="viewport"
          content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no"/>
    <meta charset="utf-8">
</head>

<body>


<div class="row cnt" style="direction: rtl">
    {% include 'base2_0/menu_item_IAC.html' %}
    {% include 'base2_0/menu_team_discription.html' %}
    <div class="col s12 m12 l8 xl8  pull-l4 pull-xl4 content" id="container">
        {% include 'base2_0/navbar.html' %}

        <div class="row" style="padding: 15px;">
            <div class="col s12 m12 l4 xl4" style="position: relative;">
                <div class="card team-summary">
                    <h1>F</h1>
                    <div class="puan">
                        <label>دقت تیم</label>
                        <label>0٪</label>
                    </div>
                    <div class="progress-bar">
                        <span class="progressed" id="filledProgress">0</span>
                    </div>
                    <button type="button" class="btn waves-effect new-code js-upload-photos">
                        بارگذاری کد
                    </button>
                    <input id="fileupload" type="file" name="code"
                           style="display: none;"
                           data-url="{% url 'online_match:file_upload_ajax' %}"
                           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
                    <!-- Modal Structure -->
                    <div id="modal1" class="modal bottom-sheet">
                        <div class="modal-content">
                            <h4>بارگذاری</h4>
                            <br>
                            <div class="progress">
                                <div class="determinate" style="width: 70%"></div>
                            </div>
                            <p class="center green-text text-darken-4" id="upload-message" hidden>بارگذاری با موفقیت
                                انجام شد</p>
                        </div>
                        <div class="modal-footer">
                            <a href="#!" class="modal-close waves-effect waves-green btn-flat">بستن</a>
                        </div>
                    </div>
                </div>
                <div class="card member" style="background-color: #3a6073; top: -13px; direction: ltr">
                    <!--carousel-->
                    <div class="carousele my-carousel carousel--translate">
                        <input class="carousel__activator" type="radio" name="carousel" id="Detail" checked="checked"/>
                        <input class="carousel__activator" type="radio" name="carousel" id="Server"/>
                        <input class="carousel__activator" type="radio" name="carousel" id="Clients"/>
                        <div class="carousel__controls">
                            <label class="carousel__control carousel__control--backward" for="Clients"></label>
                            <label class="carousel__control carousel__control--forward" for="Server"></label>
                        </div>
                        <div class="carousel__controls">
                            <label class="carousel__control carousel__control--backward" for="Detail"></label>
                            <label class="carousel__control carousel__control--forward" for="Clients"></label>
                        </div>
                        <div class="carousel__controls">
                            <label class="carousel__control carousel__control--backward" for="Server"></label>
                            <label class="carousel__control carousel__control--forward" for="Detail"></label>
                        </div>
                        <div class="carousel__track">
                            <li class="carousel__slide">
                                <img src='{% static "img/help-web-button.svg" %}' style="width: 30px;">
                                <label class="tip-title">راهنما و توضیحات</label>
                                <span class="text-article" style="top: 40%;">الگوریتم های هوشمند</span>
                                <span class="text-sub center" style="top: 55%;">سوال مسابقات و نحوه داوری ها</span>
                                <a href="{% static 'download/iac.pdf' %}" download>
                                    <div class="btn waves-effect yellow lighten-5 download-btn">
                                        دانلود فایل
                                    </div>
                                </a>
                            </li>
                            <li class="carousel__slide">
                                <img src='{% static "img/help-web-button.svg" %}' style="width: 30px;">
                                <label class="tip-title">راهنما و توضیحات</label>
                                <span class="text-article center" style="top: 40%;">دانلود دادگان مورد نیاز</span>
                                <span class="text-sub center" style="top: 55%;"></span>
                                <a href="/play/">
                                    <div class="btn waves-effect yellow lighten-5 download-btn">
                                        دانلود
                                    </div>
                                </a>
                            </li>
                            <li class="carousel__slide">
                                <img src='{% static "img/help-web-button.svg" %}' style="width: 30px;">
                                <label class="tip-title">راهنما و توضیحات</label>
                                <span class="text-article center" style="top: 40%;">لینک کانال جام</span>
                                <span class="text-sub center" style="top: 55%;left: 50%"></span>
                                <a href="http://t.me/jaam_armankadeh"
                                   download name="python_link">
                                    <div class="btn waves-effect yellow lighten-5 download-btn">
                                        ورود
                                    </div>
                                </a>

                            </li>
                        </div>
                        <div class="carousel__indicators">
                            <label class="carousel__indicator" for="Detail"></label>
                            <label class="carousel__indicator" for="Server"></label>
                            <label class="carousel__indicator" for="Clients"></label>
                        </div>
                    </div>
                    <!--end carousel-->
                </div>
            </div>
            <div class="col s12 m12 l4 xl4" style="position: relative;">
                <div class="card member yellow lighten-4">
                    <div class="card-image waves-effect waves-block waves-light">
                        <div class="pattern-back teal darken-2 waves-effect activator"></div>
                    </div>
                    <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">
                            <i class="material-icons right">more_vert</i>
                            {{ members.0.get_fname_lname }}
                        </span>
                        <p><a href="#"></a></p>
                    </div>
                    <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4">{{ members.0.get_fname_lname }}
                            <i class="material-icons right">close</i>
                        </span>
                        <p>{{ members.0.skills }}</p>
                    </div>
                </div>
                {#                <div class="card member">#}
                {#                    <div class="card-image waves-effect waves-block waves-light">#}
                {#                        <div class="pattern-back teal darken-2 waves-effect activator"></div>#}
                {#                    </div>#}
                {#                    <div class="card-content">#}
                {#                        <span class="card-title activator grey-text text-darken-4">#}
                {#                            <i class="material-icons right">more_vert</i>#}
                {#                            {{ members.1.get_fname_lname }}#}
                {#                        </span>#}
                {#                        <p><a href="#"></a></p>#}
                {#                    </div>#}
                {#                    <div class="card-reveal">#}
                {#                        <span class="card-title grey-text text-darken-4">#}
                {#                            {{ members.1.get_fname_lname }}#}
                {#                            <i class="material-icons right">close</i></span>#}
                {#                        <p>{{ members.1.skills }}</p>#}
                {#                    </div>#}
                {#                </div>#}
            </div>
            <div class="col s12 m12 l4 xl4" style="position: relative;">

                {% if members.2 %}
                    <div class="card member">
                        <div class="card-image waves-effect waves-block waves-light">
                            <div class="pattern-back teal darken-2 waves-effect activator"></div>
                        </div>
                        <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">
                            <i class="material-icons right">more_vert</i>
                            {{ members.2.get_fname_lname }}
                        </span>
                            <p><a href="#"></a></p>
                        </div>
                        <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4">{{ members.2.get_fname_lname }}
                            <i class="material-icons right">close</i>
                        </span>
                            <p>{{ members.2.skills }}</p>
                        </div>
                    </div>
                {% else %}
                    <a href="{% url 'setting:setting' 2 %}">
                        <div class="card member">
                            <div class="card-image waves-effect waves-block waves-light">
                                <div class="pattern-back teal darken-2 waves-effect activator center-align">
                                    <i class="large material-icons black-text">add_circle</i>
                                </div>
                            </div>
                            <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">
                                <i class="material-icons right">more_vert</i>
                                نام عضو جدید
                            </span>
                                <p><a href="#"></a></p>
                            </div>
                            <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4">
                            نام عضو
                            <i class="material-icons right">close</i>
                        </span>
                                <p>توضیحات کوتاه در مورد عضو جدید</p>
                            </div>
                        </div>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script>
    window.onload = function () {
        var x = document.getElementById("filledProgress").innerHTML;
        document.getElementById("filledProgress").innerHTML = "";
        document.getElementById("filledProgress").style.width = x + "%";
    }

</script>
<script src='{% static "js/jquery-3.1.1.min.js" %}'></script>
<script src="{% static 'js/jaam/item_active.js' %}"></script>
<script src='{% static "New_UI_V2/js/materialize.js" %}'></script>
<!-- upload -->
<script src="{% static 'js/jQuery-File-Upload-9.14.1/js/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jQuery-File-Upload-9.14.1/js/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jQuery-File-Upload-9.14.1/js/jquery.fileupload.js' %}"></script>
<script src="{% static 'js/photo_upload.js' %}"></script>

<script>
    M.AutoInit();

</script>
</body>

</html>

SPC_main/templates/jaam_tables.html
<html>

<head>
    <title>
        {{ user.username }} | جدول رقابت‌های جام
    </title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href='{% static "css/materialize.css" %}'>
    <link rel="stylesheet" href='{% static "css/style-global.css" %}'>
    <link rel="stylesheet" href='{% static "css/style-index.css" %}'>
    <link type="image/png" rel="icon" href="{% static 'img/jaam.png' %}">

    <meta name="viewport"
          content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no"/>
    <meta charset="utf-8">
</head>

<body>


<div class="row cnt" style="direction: rtl">
    {% if login_team.competition.competition_level < 3 %}
        {% include 'base2_0/menu_item.html' %}
    {% else %}
        {% include 'base2_0/menu_item_IAC.html' %}
    {% endif %}
    {% include 'base2_0/menu_team_discription.html' %}

    <div class="col s12 m12 l8 xl8  pull-l4 pull-xl4 content">
        {% include 'base2_0/navbar.html' %}

        <div class="section table-container">
            <h3 class="center">
                جدول لیگ اشاره‌گرهای هوشمند
            </h3>
            <table class="highlight centered responsive-table">
                <thead>
                <tr>
                    <th>تیم</th>
                    <th>دانشگاه</th>
                    <th>بازی</th>
                    <th>امتیاز</th>
                    <th>کلاس</th>
                </tr>
                </thead>

                <tbody>
                {% for team in teams.SPC %}
                    <tr>
                        <td>{{ team.user_team.username }}</td>
                        <td>{{ team.university.university_name }}</td>
                        <td>{{ team.total_games }}</td>
                        <td>{{ team.get_points }}</td>
                        <td>B</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="section table-container">
            <h3 class="center">
                جدول لیگ پردازش تصویر
            </h3>
            <table class="highlight centered responsive-table">
                <thead>
                <tr>
                    <th>تیم</th>
                    <th>دانشگاه</th>
                    <th>دقت</th>
                    <th>کلاس</th>
                </tr>
                </thead>

                <tbody>
                {% for team in teams.picture %}
                    <tr>
                        <td>{{ team.user_team.username }}</td>
                        <td>{{ team.university.university_name }}</td>
                        <td>{{ team.accuracy }}</td>
                        <td>F</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="section table-container">
            <h3 class="center">
                جدول لیگ پردازش صوت
            </h3>
            <table class="highlight centered responsive-table">
                <thead>
                <tr>
                    <th>تیم</th>
                    <th>دانشگاه</th>
                    <th>دقت</th>
                    <th>کلاس</th>
                </tr>
                </thead>

                <tbody>
                {% for team in teams.sound %}
                    <tr>
                        <td>{{ team.user_team.username }}</td>
                        <td>{{ team.university.university_name }}</td>
                        <td>{{ team.accuracy }}</td>
                        <td>F</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="section table-container">
            <h3 class="center">
                جدول لیگ پردازش متن
            </h3>
            <table class="highlight centered responsive-table">
                <thead>
                <tr>
                    <th>تیم</th>
                    <th>دانشگاه</th>
                    <th>دقت</th>
                    <th>کلاس</th>
                </tr>
                </thead>

                <tbody>
                {% for team in teams.text %}
                    <tr>
                        <td>{{ team.user_team.username }}</td>
                        <td>{{ team.university.university_name }}</td>
                        <td>{{ team.accuracy }}</td>
                        <td>F</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


    </div>

</div>
<script src='{% static "js/jquery-3.1.1.min.js" %}'></script>
<script src="{% static 'js/jaam/item_active.js' %}"></script>
<script src='{% static "New_UI_V2/js/materialize.js" %}'></script>
<script>
    M.AutoInit();

</script>
</body>

</html>